
name: CI devops 2025

# Quand est-ce que le pipeline doit se déclencher ?
on:
  push:
    branches:
      - main
      - develop
  pull_request:  # Bonus : se déclenche aussi lors des pull requests

jobs:
  test-backend:
    name: Build & Test Backend with Maven
    runs-on: ubuntu-24.04

    steps:
      # 1. Récupérer le code source du repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Installer JDK 21
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Utilisation d'Adoptium Temurin
          java-version: '21'

      # 3. Exécuter Maven (build + tests)
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml